### ISSUE TITLE
关于文章中对于对比其它网络的代码

### ISSUE THREAD

**Issue by Wang-Kaige** [cschenxiang/NeRD-Rain#3]
您好，很感谢您分享最新成果！文章中提到同传统算法、基于CNN的算法、基于Transformer的算法进行了指标对比，是否意味着对上述对比算法进行了复现呢？是否可以提供上述对比算法的复现代码以供测试呢？

**Comment by cschenxiang** [comment]
> 您好，很感谢您分享最新成果！文章中提到同传统算法、基于CNN的算法、基于Transformer的算法进行了指标对比，是否意味着对上述对比算法进行了复现呢？是否可以提供上述对比算法的复现代码以供测试呢？

您好，感谢您对我们工作的关注。我们对部分最新方法进行复现并重新进行测试，相关对比算法的代码整理如下：

DualGCN：https://xueyangfu.github.io/paper/2021/AAAI/code.zip

SPDNet：https://github.com/Joyies/SPDNet

Restormer：https://github.com/swz30/Restormer

IDT：https://github.com/jiexiaou/IDT

DRSformer：https://github.com/cschenxiang/DRSformer

其他对比算法结果我们保持与我们先前工作DRSformer的结果一致，具体细节可参考https://github.com/cschenxiang/DRSformer

**Comment by cschenxiang** [comment]
> > 您好，很感谢您分享最新成果！文章中提到同传统算法、基于CNN的算法、基于Transformer的算法进行了指标对比，是否意味着对上述对比算法进行了复现呢？是否可以提供上述对比算法的复现代码以供测试呢？
> 
> 您好，感谢您对我们工作的关注。我们对部分最新方法进行复现并重新进行测试（其他对比算法结果我们保持与我们先前工作DRSformer的结果一致，具体细节可参考[https://github.com/cschenxiang/DRSformer），相关对比算法的代码整理如下：](https://github.com/cschenxiang/DRSformer%EF%BC%89%EF%BC%8C%E7%9B%B8%E5%85%B3%E5%AF%B9%E6%AF%94%E7%AE%97%E6%B3%95%E7%9A%84%E4%BB%A3%E7%A0%81%E6%95%B4%E7%90%86%E5%A6%82%E4%B8%8B%EF%BC%9A)
> 
> DualGCN：https://xueyangfu.github.io/paper/2021/AAAI/code.zip
> 
> SPDNet：https://github.com/Joyies/SPDNet
> 
> Restormer：https://github.com/swz30/Restormer
> 
> IDT：https://github.com/jiexiaou/IDT
> 
> DRSformer：https://github.com/cschenxiang/DRSformer

**Comment by renjianyanhuo** [comment]
您好，请问该网络对算力的要求有多高，我只有一个3080的显卡，是否适合做您课题的方向呢，前辈是否能给一些建议
