### ISSUE TITLE
算力问题

### ISSUE THREAD

**Issue by renjianyanhuo** [cschenxiang/NeRD-Rain#4]
您好，请问该网络对算力的要求有多高，我只有一个3080的显卡，是否适合做您课题的方向呢，前辈是否能给一些建议，还有就是这个测试部分是否提供了权重文件

**Comment by cschenxiang** [comment]
> 您好，请问该网络对算力的要求有多高，我只有一个3080的显卡，是否适合做您课题的方向呢，前辈是否能给一些建议，还有就是这个测试部分是否提供了权重文件

您好，感谢您对我们工作的关注。该方法预计在一张3080的显卡上可以训练，但训练可能比较耗时，测试没问题。权重文件在readme->Pre-trained Models里面已经提供。

**Comment by renjianyanhuo** [comment]
> > 您好，请问该网络对算力的要求有多高，我只有一个3080的显卡，是否适合做您课题的方向呢，前辈是否能给一些建议，还有就是这个测试部分是否提供了权重文件
> 
> 您好，感谢您对我们工作的关注。该方法预计在一张3080的显卡上可以训练，但训练可能比较耗时，测试没问题。权重文件在readme->Pre-trained Models里面已经提供。
您好，我还想问一下，您的电脑配置是什么，有几张卡，训练一次3000轮，大约需要多长时间呢？

**Comment by renjianyanhuo** [comment]
您好，我还想问一下，您的电脑配置是什么，有几张卡，训练一次3000轮，大约需要多长时间呢？

**Comment by cschenxiang** [comment]
> 您好，我还想问一下，您的电脑配置是什么，有几张卡，训练一次3000轮，大约需要多长时间呢？

您好，正如我们论文中所述：We train on one NVIDIA GeForce RTX 3090 GPU. We train the SPA-Data dataset for 10 epochs, the DID-Data and DDN-Data datasets for 200 epochs, and the Rain200L and Rain200H datasets for 600 epochs. 

训练时间和不同数据集数量相关，我们在Rain200L/H预计训练5天左右~

当然，您可以增大batch size和GPU数量等策略来加速训练。

**Comment by ll000x** [comment]
训练时候的输入图片好像有大小要求，请问 
怎么回事呀
